name: build

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      with:
        key: env-files-win
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: chmod +x ./setup.bat
    - run: chmod +x ./build.sh
    - run: .\setup.bat
    - run: ./build.sh -p Windows
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: enhanced-vanilla-shader-windows
        path: ./build/Windows
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      with:
        key: env-files-linux
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: chmod +x ./setup.sh
    - run: chmod +x ./build.sh
    - run: ./setup.sh
    - run: ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: enhanced-vanilla-shader-android
        path: ./build/Android
  ios:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        key: env-files-linux
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: chmod +x ./setup.sh
    - run: chmod +x ./build.sh
    - run: ./setup.sh
    - run: ./build.sh -p iOS
    - uses: actions/upload-artifact@v4
      with:
        name: enhanced-vanilla-shader-ios-materials
        path: ./build/iOS     
  windows_ne:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      with:
        key: env-files-win
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: chmod +x ./setup21.bat
    - run: chmod +x ./build21.sh
    - run: .\setup21.bat
    - run: ./build21.sh -p Windows
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: enhanced-vanilla-shader-windows
        path: ./build/Windows_NE
  android_ne:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      with:
        key: env-files-linux
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: chmod +x ./setup21.sh
    - run: chmod +x ./build21.sh
    - run: ./setup21.sh
    - run: ./build21.sh
    - uses: actions/upload-artifact@v4
      with:
        name: enhanced-vanilla-shader-android
        path: ./build/Android_NE
  ios_ne:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        key: env-files-linux
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: chmod +x ./setup21.sh
    - run: chmod +x ./build21.sh
    - run: ./setup21.sh
    - run: ./build21.sh -p iOS
    - uses: actions/upload-artifact@v4
      with:
        name: enhanced-vanilla-shader-ios-materials
        path: ./build/iOS_NE
